### ISSUE TITLE
Cease and desist

### ISSUE THREAD

**Issue by andreis** [raluca-elena/fuel#1]
Hi

I represent my client, Nike Inc., and would kindly ask you to cease and desist your infringing activities. We're the trademark owners of Nike+ Fuel, and of any words related to _liquid capable of catching fire_.

Bafta delo delo
Nike people

http://en.wikipedia.org/wiki/NikeFuel

**Comment by andreis** [comment]
Please also notice I have starred your repo. You're welcome!

**Comment by raluca-elena** [comment]
Multam mister Andrei and see you in court! :p

On Thu, Apr 23, 2015 at 4:38 PM, Andrei Simionescu <notifications@github.com

> wrote:
> 
> Please also notice I have starred your repo. You're welcome!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/raluca-elena/fuel/issues/1#issuecomment-95748550.

## 

Raluca-Elena

**Comment by andreis** [comment]
Case closed, the defendant chickened out.
